name: Smart Gate
version: 1.0.2
slug: smart_gate
description: Automatic license plate recognition gate opener with smart notifications
url: https://github.com/andreaemmanuele/haos_smartgate
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
host_network: true
hassio_api: true
homeassistant_api: true
map:
  - config:rw
options:
  motion_entity: binary_sensor.ingresso_veicolo
  camera_entity: camera.ingresso_high_quality
  gate_switch: switch.cancello
  cooldown_sec: 120
  allowed_plates:
  snapshot_path: /config/www/smart_gate/latest-snapshot.jpg
  roi: "0.0,0.0,1.0,1.0"
  model_path: /config/www/smart_gate/model.onnx
  confidence: 0.5
  history_dir: /config/www/smart-gate/history
  keep_history: false
  debug: false
schema:
  motion_entity: str
  camera_entity: str
  gate_switch: str
  cooldown_sec: int
  allowed_plates: [str]
  snapshot_path: str
  roi: str
  model_path: str
  confidence: float
  history_dir: str
  keep_history: bool
  debug: bool
