name: Smart Gate
version: 1.2.2
slug: smart_gate
description: Automatic AI powered license plate recognition gate opener
url: https://github.com/haos-eco/smart-gate
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
host_network: true
hassio_api: true
homeassistant_api: true
map:
  - config:rw
options:
  motion_entity: binary_sensor.ingresso_veicolo
  camera_entity: camera.ingresso_high_quality
  gate_switch: switch.cancello
  cooldown_sec: 120
  allowed_plates:
  roi: "0.0,0.0,1.0,1.0"
  confidence: 0.5
  min_yolo_score: 0.65
  min_ocr_confidence: 0.75
  model_path: /config/www/smart_gate/models/yolo/model.onnx
  snapshot_path: /config/www/smart_gate/snapshot/latest.jpg
  history_dir: /config/www/smart_gate/snapshot/history
  debug_path: /config/www/smart_gate/snapshot/last_plate_crop.jpg
  keep_history: false
  gpu: false
  debug: false
  notify_devices:
  visitor_stop_sec: 5
  notification_sound: default
schema:
  motion_entity: str
  camera_entity: str
  gate_switch: str
  cooldown_sec: int
  allowed_plates:
    - plate: str
      person_entity: str?
  roi: str
  confidence: float
  min_yolo_score: float
  min_ocr_confidence: float
  notify_services:
    - str
  visitor_stop_sec: int?
  notification_sound: str?
  keep_history: bool
  gpu: bool
  debug: bool
